version: '3.3'

services:
  fa-admin-server:
    # 指定镜像
    image: farando/fa-admin-web:latest
    container_name: fa-admin
    restart: always
    ports:
      # 端口映射
      - "8000:80"
      # socketio端口
      - "18081:18081"
    volumes:
      - ${DATA_DIR}/fa-admin/file:/opt/fa-admin/file
      - ${DATA_DIR}/fa-admin/log:/opt/fa-admin/log
      - ./services/fa-admin/application-docker.yml:/opt/fa-admin/application-docker.yml
    environment:
      - TZ=$TZ
    depends_on:
      - fa-admin-mysql5
      - fa-admin-redis7
    networks:
      - fa_admin

  fa-admin-mysql5:
    # image: mysql:${MYSQL5_VERSION}
    image: farando/fa-admin-mysql:5.7
    build: ./docker/mysql
    container_name: fa-admin-mysql5.7
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    restart: always
    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD=123456
      - character-set-client-handshake=FALSE
      - max_allowed_packet=1048576000
      - wait_timeout=288000
    networks:
      - fa_admin

  fa-admin-redis7:
    image: 'redis:7.0.5'
    container_name: fa-admin-redis7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./services/redis:/usr/local/etc/redis
      - ${DATA_DIR}/redis:/data/:rw
    command: 'redis-server --requirepass fa@redis#1276'
    networks:
      - fa_admin

  fa-admin-php-redis-admin:
    image: 'erikdubbelboer/phpredisadmin:latest'
    container_name: fa-admin-php-redis-admin
    restart: always
    ports:
      - '8182:80'
    environment:
      - REDIS_1_HOST=fa-admin-redis7
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=fa@redis#1276
      - REDIS_1_NAME=local
    networks:
      - fa_admin

#  fa-admin-nginx:
#    image: nginx:latest
#    container_name: "nginx"
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ${DATA_DIR}/nginx/log/:/var/log/nginx/
#      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
#      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
#    networks:
#      fa_admin:

networks:
  fa_admin:
    driver: bridge
